name: register_system
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

dependencies:
  args: ^2.4.0
  dotenv: ^4.2.0
  email_validator: ^2.1.17
  encrypt: ^5.0.3
  mongo_dart: ^0.10.1
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  http: ^1.1.0
  lints: ^3.0.0
  test: ^1.24.0
